spring.application.name=springboot-jpa
spring.datasource.url=jdbc:mysql://localhost:3306/db_jpa_crud
spring.datasource.username=root
spring.datasource.password=sasa1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Para mostrar las consultas SQL en consola
spring.jpa.show-sql=true

# Valida y genera tablas siempre 
spring.jpa.hibernate.ddl-auto=update
# Para que no se muestre el error de que no se puede crear la tablas
spring.sql.init.mode=always

# Colores en consola
spring.output.ansi.enabled=ALWAYS

# Para reiniciar la aplicación automáticamente
spring.devtools.restart.enabled=true

# Esto evita inicializar todos los beans al inicio y solo carga lo necesario.
spring.main.lazy-initialization=true

spring.web.resources.add-mappings=false