config.code=23232
config.username=jonas
config.message=Hola que tal?
config.listOfValues=hola,que,tal
config.valueMap={product:'CPU Intel Core i7 12700k', description:'litografia de 7 nanometros, 10 nucleos, 16 hilos, 5.1 GHz', price:'1000'}
config.user={name:'Oscar Vladimir', lastname='Benites', email='oscar@gmail.com'}